### ISSUE TITLE
Saving Sass files crashes Browser Sync

### ISSUE THREAD

**Issue by thedavideck** [maepon/bs4vccw_s#2]
Anytime I make a change to my style.scss file; localhost:3000 crashes.. here is my error log. 

Any information would be greatly appreciated
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bs4vccw_s@0.0.1~prestart: bs4vccw_s@0.0.1
6 info lifecycle bs4vccw_s@0.0.1~start: bs4vccw_s@0.0.1
7 verbose lifecycle bs4vccw_s@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle bs4vccw_s@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/davideck/Desktop/vccw/bs4vccw_s/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle bs4vccw_s@0.0.1~start: CWD: /Users/davideck/Desktop/vccw/bs4vccw_s
10 silly lifecycle bs4vccw_s@0.0.1~start: Args: [ '-c', 'gulp' ]
11 silly lifecycle bs4vccw_s@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle bs4vccw_s@0.0.1~start: Failed to exec start script
13 verbose stack Error: bs4vccw_s@0.0.1 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:887:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid bs4vccw_s@0.0.1
15 verbose cwd /Users/davideck/Desktop/vccw/bs4vccw_s
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.0.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error bs4vccw_s@0.0.1 start: `gulp`
22 error Exit status 1
23 error Failed at the bs4vccw_s@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by thedavideck** [comment]
this is what I get in Terminal when it happens:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bs4vccw_s@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bs4vccw_s@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
